services:
  - type: web
    name: bug-whisperer
    env: node
    plan: free
    buildCommand: npm install && npm run install-frontend && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000